name: demo ucrop

on:
  push:
    branches: [ "demo" ]

permissions:
  contents: write # Дает право боту создать ветку gh-pages для работающего сайта

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install and Build React
      run: |
        cd main-interface
        npm ci
        npm run build --if-present

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: main-interface/build # Если вы используете Vite вместо CRA, замените build на dist
        branch: gh-pages # Сюда загрузится чистый HTML/JS работающего сайта
